### ISSUE TITLE
level editor

### ISSUE THREAD

**Issue by jorisBarkema** [jensj12/MeesGame#1]
- [x] loading exitisting levels not implemented
- [x] saving created levels
- [x] walking over special tiles would probably cause the editor player to move to
- [x] interface looks terrible
- [x] editing properties of special tiles, such as doors and keys, is not yet possible
- [x] updating the tilefield is slow and causes a noticeable lag spikes when many walls are on the level

**Comment by nessemis** [comment]
issues:
-loading exitisting levels not implemented
-saving created levels
-walking over special tiles would probably cause the editor player to move to
-interface looks terrible
-editing properties of special tiles, such as doors and keys, is not yet possible
-ascending and descending levels isn't implemented

-updating the tilefield is slow and causes a noticeable lag spikes when many walls are on the level
