### ISSUE TITLE
Player starts in upper left corner

### ISSUE THREAD

**Issue by LisanneW** [jensj12/MeesGame#114]
On generating a random maze the player can start in the upper left corner, on the wall :(

![image](https://cloud.githubusercontent.com/assets/22234226/21687879/3a01fc1e-d36b-11e6-872e-1e7593480958.png)

**Comment by jensj12** [comment]
This is the default location if the start tile can't be found. That means I need to check for removed starttiles while generating (or add it at the end).

**Comment by maxmeijer42** [comment]
Is this fixed yet?

**Comment by jensj12** [comment]
The improved maze generator doesn't place keys on starttiles, if it does, please reopen this issue.
