### ISSUE TITLE
RandomWalker AI broken

### ISSUE THREAD

**Issue by jensj12** [jensj12/MeesGame#143]
MC AI also stopped working (sometimes just walking east-south-east-south blindy, getting stuck when it's not possible), so it may have something to do with the changed game logic in the ice tile PR.

RandomWalker often gets stuck in a corner. In the attached level (rename it to .lvl), it always walks to the right and stops.
[DummyTestLevel.txt](https://github.com/jensj12/MeesGame/files/708017/DummyTestLevel.txt)

**Comment by maxmeijer42** [comment]
Yes, that's true, I'm going to change the IAI interface a little bit
