### ISSUE TITLE
Project dossier

### ISSUE THREAD

**Issue by jensj12** [jensj12/MeesGame#205]
(half copied from website, and thus in dutch)
 - [x] het projectdocument
 - [x] je eindproduct (gedocumenteerde source, executable)
 - [x] de gebruikershandleiding
 - [x] je eindverslag
 - [x] de sources van je website
 - [x] een readme file (zie hieronder)
 - [x] volledig logboek
 - [x] honours document

**Comment by jorisBarkema** [comment]
is 'de sources van je website' just the source code?

**Comment by jensj12** [comment]
'The sources' means everything needed to make the website work locally. This includes (but is not limited to) images and source code.

**Comment by jorisBarkema** [comment]
Oh great that's already on the drive
