### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by jensj12** [jensj12/MeesGame#77]
- [x] Main theme
- [x] Walking through doors
- [x] Using portals
- [x] Button click
- [x] scream when dying/getting caught

**Comment by jorisBarkema** [comment]
Alright I uploaded sound files (.wav) to a new branch 'sound'. They're in content, just like the sprites, you should be ready to go @twjvdhorst .

**Comment by jensj12** [comment]
@jorisBarkema You can throw them into a PR so they're in the main branch. Saves extra conflicts in content later on.

**Comment by jensj12** [comment]
@jorisBarkema Please change the main theme, it's not prison-related, contains spoken text and I doubt it's legal to use it.

**Comment by jorisBarkema** [comment]
we can just use the first minute or so of it, so no text, and it's straight from youtube so I don't think that'll be a problem.

**Comment by jorisBarkema** [comment]
But we can use this one as well

https://www.youtube.com/watch?v=C5t_ovNHk5M

**Comment by jensj12** [comment]
'Straight from youtube'...
Anything on youtube is licenced with either the standard youtube licence or creative commons. Please link to the licence and where it states that we may use it.

**Comment by jorisBarkema** [comment]
I don't remember but this one is Creative Commons Attribution license (reuse allowed)

https://www.youtube.com/watch?v=vPwGmJaW99Y

just put this somewhere in a comment and it's definitely good.

**Comment by jorisBarkema** [comment]
@twjvdhorst Here i a sound effect for ladder climbing to use when going through a portal.

I think the one starting around 0:09 is best. https://www.youtube.com/watch?v=tuq_f7WzcY0. creative commons license.

**Comment by jorisBarkema** [comment]
@twjvdhorst Walking sounds a bit weird, I don't know if it's a quick fix or not, if it is would be great but very low priority.
